### ISSUE TITLE
about model.py

### ISSUE THREAD

**Issue by YoungJoongUNC** [YapengTian/TDAN-VSR-CVPR-2020#14]
Hello!

In model.py line 219 - 223

`batch_size, num, ch, w, h = x.size()  # 5 video frames`
`# center frame interpolation`
`center = num // 2`
`# extract features`
`y = x.view(-1, ch, w, h)`

Shouldn't the order of w and h be changed as follows?

`batch_size, num, ch, h, w = x.size()  # 5 video frames`
`# center frame interpolation`
`center = num // 2`
`# extract features`
`y = x.view(-1, ch, h, w)`

**Comment by YapengTian** [comment]
Haha~ Yes, the order: "h, w" is better. But, it will not affect results. In addition, you could use more gpus for fast training and fine-tuning can improve  performance (for example, we can first train the model from lr=1e-4. After 600 epochs, we can fine-tune the model with lr=5e-5. It is pretty similar to training strategy in EDVR.)

**Comment by YoungJoongUNC** [comment]
Thank you a lot for your fast reply :)
