### ISSUE TITLE
SourceChangeWarning

### ISSUE THREAD

**Issue by YoungJoongUNC** [YapengTian/TDAN-VSR-CVPR-2020#16]
Hello!
While I was playing with your code (model.py) I encountered following warning:
```
SourceChangeWarning: source code of class 'model.TDAN_VSR' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
```
I did insert some codes between your codes in model.py like plotting the intermediate feature. Is this just minor warning that is caused just because I insert some new codes into your code? Could this warning can be just ignored?

**Comment by YapengTian** [comment]
Just ignore it. It will not affect performance.

**Comment by YoungJoongUNC** [comment]
Thank you!
