### ISSUE TITLE
An error was encountered at runtime

### ISSUE THREAD

**Issue by zzhh0622** [YapengTian/TDAN-VSR-CVPR-2020#21]
Thanks for your code.
When run eval.py, something went wrong, the error is as follows, what should I do.
torch.FatalError: invalid argument 5: 4D weight tensor (nOutputPlane,nInputPlane,kH,kW) expected, but got: (null) at /mnt/ssd0/project/ytian21/videoSR/DCN/src/deform_conv_cuda.c:15

**Comment by zzhh0622** [comment]
I know this is a problem of default path,but I can't find where to change.

**Comment by YapengTian** [comment]
Did you re-compile the deformable conv?

**Comment by zzhh0622** [comment]
Do you mean the second step in readme（bash make.sh）.
I have done that.

**Comment by YapengTian** [comment]
Successfully? In addition, what data you are testing now?

**Comment by YapengTian** [comment]
Did you follow the instructions to install pytorch-031?

**Comment by zzhh0622** [comment]
No error.But I don't how to cofirm if is successful.I use the test-date you support.

**Comment by zzhh0622** [comment]
I use pytorch-041.Let me try 0-3-1.

**Comment by YapengTian** [comment]
Yes, please try pytorch031 and compile dconv again.

**Comment by zzhh0622** [comment]
It's OK now.
Thanks for your reply.

**Comment by hubeichenxing** [comment]
Hello，i have encountered the same problem，when i install pytorch031，compile dconv and run eval.py， it report the error：
Traceback (most recent call last):
  File "eval.py", line 6, in <module>
    import torch
  File "/opt/conda/lib/python3.6/site-packages/torch/__init__.py", line 320, in <module>
    import torch.distributions
  File "/opt/conda/lib/python3.6/site-packages/torch/distributions/__init__.py", line 77, in <module>
    from .categorical import Categorical
  File "/opt/conda/lib/python3.6/site-packages/torch/distributions/categorical.py", line 2, in <module>
    from torch._six import nan
ImportError: cannot import name 'nan'
Do you know how to fix it ? Thanks.

**Comment by YapengTian** [comment]
Sorry for the late response. It seems that PyTorch is well installed.
