### ISSUE TITLE
Questions about citation of this article

### ISSUE THREAD

**Issue by BIOINSu** [YapengTian/TDAN-VSR-CVPR-2020#23]
Dear authors,
This is a great work and i would like to cite this paper in my own article. May i ask is there any difference between the CVPR 2020 version and the arxiv version ? 
It seems that the arxiv version is published in 2018. I wonder if there is any improvement in CVPR 2020 version? Or if the performance is totally the same? 
Thanks a lot !

**Comment by YapengTian** [comment]
Thanks for citing our work.  The differences between the arxiv and cvpr versions are: 
(1) better performance; (2) experiments to validate and explain the alignment network.

Thanks!

**Comment by YapengTian** [comment]
The released model (bicubic downsampling) in this repo. is associated with our CVPR version.

**Comment by BIOINSu** [comment]
Thanks for the reply ! The pretrained model can be run successfully. Issue close.
