### ISSUE TITLE
How to test images with psnr?

### ISSUE THREAD

**Issue by wwlCape** [YapengTian/TDAN-VSR-CVPR-2020#25]
Thanks for your great work. I want to test  my datasets, would you please tell how to generate PSNR and SSIM values during testing?

**Comment by YapengTian** [comment]
Thanks for your interest.
https://github.com/yulunzhang/RDN/tree/master/RDN_IR/RDN_TestCode/RDN_SR_RGB provides PSNR and SSIM evaluation functions. It should be easy to use it to do testing.

**Comment by wwlCape** [comment]
Ok, thank you for replying!
