### ISSUE TITLE
cuda runtime error: out of memory 

### ISSUE THREAD

**Issue by EAGLE50** [YapengTian/TDAN-VSR-CVPR-2020#28]
Firstly,the /data/SPMCs/AMVTG_004 data is valid. Unfortunately,I got a error, when I use my dataset that the size of image 1280*720 .
error:cuda runtime error:out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

File ./functions/deform_conv.py , line 37, in forward
output=input.new(*self._output_size(intput,weight))

what should I do? thanks

**Comment by YapengTian** [comment]
Sorry for the late response. I was working on PhD thesis proposal.

One commonly used way is to split the full images into image patches and then compose the generate patches to full images again. https://github.com/YapengTian/TDAN-VSR-CVPR-2020/blob/master/solver.py pls look at the chop_forward function.
