### ISSUE TITLE
x2 model

### ISSUE THREAD

**Issue by ycjing** [YapengTian/TDAN-VSR-CVPR-2020#34]
Hi @YapengTian 

Thank you for the great work! Is it possible to train a 2x VSR model with the training code? Thank you!

Best,
Yongcheng

**Comment by YapengTian** [comment]
Yes, it can train a 2x model after changing the upscaling factor to 2 from 4.

**Comment by ycjing** [comment]
Hi @YapengTian 

Thank you for the response! I appreciate it. May I ask is there anything else that should be changed in the code other than the parameter of upscaling factor? Thank you!

Best,
Yongcheng

**Comment by YapengTian** [comment]
No, I think only the upscaling factor parameter in train and dataloader functions needs to be modified.

**Comment by ycjing** [comment]
Hi @YapengTian 

Thank you for the quick response! I really appreciate it. Wish you all the best!

Best,
Yongcheng
