### ISSUE TITLE
.so problem

### ISSUE THREAD

**Issue by lucky-kims36** [YapengTian/TDAN-VSR-CVPR-2020#39]
Hi,

I tried to evaluation your projects, but faced the error message below.

.../TDAN/_ext/deform_conv/_deform_conv.so: undefined symbol: state

Some articles on the web told me that the version of compiler making .so file maybe different.
  gcc version in my system is 4.8.5.

Could you guide to make .so file myself?
Or, are there any other reasons?

Thanks.

**Comment by YapengTian** [comment]
I did not meet the issue before. I think you do not need to make a .so file. Could you install Pytorch-0.3.1 and then compile the deformable Conv?

**Comment by lucky-kims36** [comment]
Thanks for your answer.

I changed my gcc version to 7.4.0 and the problem solved.

Sorry to bother you with this issue.

**Comment by lucky-kims36** [comment]
Thanks for your answer.

I changed my gcc version to 7.4.0 and the problem solved.

Sorry to bother you with this issue.

**Comment by lucky-kims36** [comment]
Thanks for your answer.

I changed my gcc version to 7.4.0 and the problem solved.

Sorry to bother you with this issue.
