### ISSUE TITLE
How to make LR frames?

### ISSUE THREAD

**Issue by reminayano** [YapengTian/TDAN-VSR-CVPR-2020#40]
Hi, I tried to make BD data from HR.
What is kernel size and standard deviation?

**Comment by YapengTian** [comment]
I used the BD resizing code from the RDN https://github.com/yulunzhang/RDN/blob/master/RDN_IR/RDN_TestCode/RDN_SR_RGB/Prepare_TestData_HR_LR.m.

**Comment by reminayano** [comment]
OK, thank you.
