### ISSUE TITLE
I encountered severe artifact when testing on VID4 with pretrained model

### ISSUE THREAD

**Issue by T5eng** [YapengTian/TDAN-VSR-CVPR-2020#41]
as described in the title, here is some cases. But case calendar is alright, same as visual quality in the paper.
![image](https://user-images.githubusercontent.com/14946599/97069276-d0df3700-1601-11eb-84ce-e70e4fb435e7.png)

![image](https://user-images.githubusercontent.com/14946599/97069295-e6ecf780-1601-11eb-828f-0ebcc5df15e6.png)

![image](https://user-images.githubusercontent.com/14946599/97069302-f0765f80-1601-11eb-8c03-ba7f20693987.png)

It would be great if  you could help solve this problem.

**Comment by YapengTian** [comment]
The released model is for BI setting. It means that you need to use Matlab resize function with the "bicubic" option to downsample HR frames to generate LR frames.

**Comment by T5eng** [comment]
In my experiment, LR frames are generated with `cv2.resize(... , interpolation=cv2.INTER_CUBIC)` and frames in calendar set are all looking good. Artifact exists only in foliage, city and walk set... so weird...

**Comment by YapengTian** [comment]
The functions in OpenCV and Matlab should be different. I guess you will have the similar issue if you test the generated LR frames using other BI models. But, I also cannot understand why the results of the calendar sequence are good.

**Comment by T5eng** [comment]
I tried to generate LR with Matlab bicubic interpolation. But artifact still exists.....

**Comment by YapengTian** [comment]
Could you use this code: https://github.com/yulunzhang/RDN/blob/master/RDN_IR/RDN_TestCode/RDN_SR_RGB/Prepare_TestData_HR_LR.m? The BI setting.

**Comment by T5eng** [comment]
It works. It seems this and some other similar methods are functioning on very specifically degredation....
