### ISSUE TITLE
cuda runtimt error(2): out of memory

### ISSUE THREAD

**Issue by candygogogogo** [YapengTian/TDAN-VSR-CVPR-2020#44]
The same environment, but I showed up out of memory.(RTX2070  8G ；batch size =  1)
Ask for your help

**Comment by YapengTian** [comment]
One commonly used way is to split the full images into image patches and then compose the generate patches to full images again. https://github.com/YapengTian/TDAN-VSR-CVPR-2020/blob/master/solver.py pls look at the chop_forward function.

**Comment by candygogogogo** [comment]
Yes, the article cuts the pictures into four parts. Do you mean let me cut the picture a little smaller? 
（I am very surprised by your timely reply. Thank you very much.）

**Comment by candygogogogo** [comment]
I solved this problem. Thank you very much for your recovery. I wish you another good work in 2021

**Comment by candygogogogo** [comment]
I solved this problem. Thank you very much for your recovery. I wish you another good work in 2021
