### ISSUE TITLE
TDAN在自己的数据集训练效果很差

### ISSUE THREAD

**Issue by CNHNLP** [YapengTian/TDAN-VSR-CVPR-2020#47]
TDAN在自己的数据集训练效果很差，效果都不及双三次插值方法

**Comment by YapengTian** [comment]
抱歉 邮件没收到提醒 刚看到你的问题。 不知道你的训练数据怎么准备的？

**Comment by CNHNLP** [comment]
> 抱歉 邮件没收到提醒 刚看到你的问题。 不知道你的训练数据怎么准备的？

根据dataset.py文件准备的，将帧序列保存为图片。学习率设为4e-4时模型很容易崩溃，减小学习率后模型收敛效果不及插值方法。请问您训练就是train.py中默认配置吗?

**Comment by YapengTian** [comment]
对的 我用的就是默认的这些参数 比如lr应该是1e-4在vimeo上做的训练 比较稳定

**Comment by YapengTian** [comment]
不知道你的是不是bicubic降采样的数据 如果你的退化kernel不是中心对称的话，代码里的一些数据增强的方法比如旋转之类的可能带来负面影响

**Comment by CNHNLP** [comment]
> 不知道你的是不是bicubic降采样的数据 如果你的退化kernel不是中心对称的话，代码里的一些数据增强的方法比如旋转之类的可能带来负面影响
降采样的数据是通过Matlab imresize函数进行的插值退化操作，“imresize(img, 1/up_scale, 'bicubic')”

**Comment by YapengTian** [comment]
这跟我之前用的降采样code是一样的 这就很奇怪了 你用我训练好的模型测试有问题吗

**Comment by CNHNLP** [comment]
用你训练好的模型测试效果还可以，但是自己训练的话效果就很差；还有请问您方便分享2倍和3倍的模型吗？

**Comment by YapengTian** [comment]
我之前只训练了4倍的因为大家之前一般就用这个factor。https://github.com/YapengTian/TDAN-VSR-CVPR-2020/blob/master/SR_datasets.py 如果用不同的scale你需要改下这里

**Comment by YapengTian** [comment]
这里有个scale=4的参数，另外就是我假定只使用5张训练图片，如果你的训练数据集比如是用的reds或别的一个训练sequence很长的话，这个dataloader可能不太试用因为每次只采五张太少了

**Comment by CNHNLP** [comment]
嗯嗯  好的 我在训练一下看看把  谢谢您的回复

**Comment by YapengTian** [comment]
嗯嗯 不用客气
