### ISSUE TITLE
请问可以提供一个scale=2的模型嘛？

### ISSUE THREAD

**Issue by ShammyFu** [YapengTian/TDAN-VSR-CVPR-2020#52]
您好！这个项目很棒~ 用您提供好的model.pt在我们的数据集上测试后效果很好，但是这个模型是scale=4的。在我们的工作中需要比对scale=2的模型效果，如果方便的话，请问可以提供吗？十分感谢~望得到回复！

**Comment by YapengTian** [comment]
非常抱歉那么晚回复。 因为之前大家通用的对比都是在四倍上，所以我也没有现成的2倍模型。不过通过改scale参数，我们可以训练2倍的模型。
