### ISSUE TITLE
关于数据集的放置

### ISSUE THREAD

**Issue by zqw-123** [YapengTian/TDAN-VSR-CVPR-2020#54]
作者您好，我感觉这篇论文对我很有用，目前想要用自己的数据集测试一下，但苦于不知道文件目录如何处理，希望您有时间能解答一下，谢谢！

**Comment by YapengTian** [comment]
可以参考提供的样例：https://github.com/YapengTian/TDAN-VSR-CVPR-2020/tree/master/data 来组织数据。
