### ISSUE TITLE
关于训练!

### ISSUE THREAD

**Issue by luoguangguang** [YapengTian/TDAN-VSR-CVPR-2020#55]
parser.add_argument('--train-set', metavar='T', type=str, default=**'data/VSR_data/train'**,
                    help='data set for training. Default train')
parser.add_argument('--test-set', metavar='NAME', type=str, default='**data/VSR_data/val/Temple**',
                    help='dataset for testing. Default Temple from SPMC  dataset')

你好，我想问一下这两个文件我要怎么去找到呢！ 谢谢

**Comment by YapengTian** [comment]
我上传这个用于val的temple set：https://github.com/YapengTian/TDAN-VSR-CVPR-2020/tree/master/data/val/Temple。training set太大了，我使用的vimeo-90k的训练集， 可以从这里获取http://toflow.csail.mit.edu/。

**Comment by luoguangguang** [comment]
谢谢你，请问vimeo-90k是下载 82G 那个吗
还有我在运行train的时候遇到PermissionError: [Errno 13] Permission denied: '/checkpoint'  这个问题
运行build的时候VerificationError: CompileError: command 'gcc' failed with exit status 1
运行eval.py的时候  RuntimeError: NCCL Error 2: system error
或者，你可以简要跟我说一下啊实行的步骤吗，谢谢你

**Comment by luoguangguang** [comment]
谢谢你，还有
运行build.py的时候致命错误：cuda.h：没有这样的文件或目录

或者，你可以简要跟我说一下实行的步骤吗，谢谢你
或者，要执行什么文件可以看到一些直观的结果呢

**Comment by YapengTian** [comment]
你不需要运行build.py，如果需要编译dcn的话，直接跑bash make.sh 就好。如果你只需要测试的话，可以运行 python eval.py -t test_dataset_path，我提供了一些测试数据在https://github.com/YapengTian/TDAN-VSR-CVPR-2020/tree/master/data
如果你需要训练的话，需要运行的文件是 train.py.
