### ISSUE TITLE
关于训练过程时将checkpoint 和verbose打开的问题

### ISSUE THREAD

**Issue by luoguangguang** [YapengTian/TDAN-VSR-CVPR-2020#56]
File "/home/***/TDAN-VSR/solver.py", line 236, in _epoch_step
    bar.update(i,force=True)
 TypeError: update() got an unexpected keyword argument 'force'

我不知道是不是版本的问题

**Comment by luoguangguang** [comment]
或许，可以请问您一下progressbar的版本是多少吗

**Comment by YapengTian** [comment]
对这里问题是在progressabar， 可以这样安装：pip install progressbar2
