### ISSUE TITLE
请问哪里有两种退化方法训练的模型

### ISSUE THREAD

**Issue by Mwy98** [YapengTian/TDAN-VSR-CVPR-2020#57]
您好，论文中提到用BI和BD两种退化方法训练了两种模型，想请问哪里可以找到

**Comment by YapengTian** [comment]
BI 和 BD的模型可以在这里看到：https://github.com/YapengTian/TDAN-VSR-CVPR-2020/tree/master/model 
BD退化使用的是RDN里BD的code： https://github.com/yulunzhang/RDN/blob/master/RDN_IR/RDN_TestCode/RDN_SR_RGB/Prepare_TestData_HR_LR.m

**Comment by Mwy98** [comment]
好的，谢谢您！
